main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Posts
    pageRef: /posts
    weight: 20
  - name: Categories
    pageRef: /categories
    weight: 25
  - name: Tags
    pageRef: /tags
    weight: 30
