description: |
  Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.
license: |
  Except as otherwise noted, the content of this page is licensed under the [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en), and code samples are licensed under the [MIT License](https://raw.githubusercontent.com/zhanglianxin/blog/refs/heads/master/LICENSE-CODE).
mainSection: Tech
defaultAuthor: main
authors:
  main:
    name: Coolman
    avatar: https://avatars.githubusercontent.com/u/9329713?v=4
    bio: |
      Debitis assumenda esse dignissimos aperiam delectus maxime tenetur repudiandae dolore
    links:
      github: https://github.com/zhanglianxin
      cfemail: 7c111d15100813461f131310111d123c1f131310111d12520f150819
      bluesky: https://bluesky.social
